const departmentAbbreviations = [
	{id: "ArtArch", text: "Art History and Archaeology"},
	{id: "GIS", text: "Geographic Information Systems"},
	{id: "Greek", text: "Greek"},
	{id: "XCORE", text: "Design & Visual Arts - Core"},
	{id: "Bus", text: "Business"},
	{id: "Hist", text: "History"},
	{id: "MILS", text: "Military Science"},
	{id: "WGSS", text: "Women, Gender, and Sexuality Studies"},
	{id: "RelSt", text: "Religious Studies"},
	{id: "MPH", text: "Master of Public Health"},
	{id: "BEE", text: "Brookings Executive Education"},
	{id: "SYSIN", text: "Systems Integration"},
	{id: "URST", text: "Urban Studies"},
	{id: "Physics", text: "Physics"},
	{id: "EAsia", text: "East Asian Studies"},
	{id: "Mus", text: "Music"},
	{id: "MLA", text: "Master of Liberal Arts"},
	{id: "Korean", text: "Korean"},
	{id: "GSAS", text: "Graduate School"},
	{id: "ARCH", text: "Architecture"},
	{id: "Music", text: "Music"},
	{id: "Sci", text: "Science"},
	{id: "GSever", text: "Sever Institute"},
	{id: "AMCS", text: "American Culture Studies"},
	{id: "MAIR", text: "Military Aerospace Science"},
	{id: "Psych", text: "Psychology"},
	{id: "IRISH", text: "Irish"},
	{id: "Chem", text: "Chemistry"},
	{id: "Engr", text: "General Engineering"},
	{id: "ETEM", text: "Engineering Management"},
	{id: "SOC", text: "Sociology"},
	{id: "ChSt", text: "Children's Studies"},
	{id: "Spch", text: "Speech and Hearing Sciences"},
	{id: "IAS", text: "International & Area Studies"},
	{id: "JINE", text: "Jewish, Islamic and Near Eastern Languages and Cultures"},
	{id: "LatAm", text: "Latin American Studies"},
	{id: "INFO", text: "Information Management"},
	{id: "Film", text: "Film and Media Studies"},
	{id: "History", text: "History"},
	{id: "HBRW", text: "Hebrew"},
	{id: "PHS", text: "Public Health Sciences"},
	{id: "SWDP", text: "Social Work Direct Practice"},
	{id: "Focus", text: "Focus"},
	{id: "ARC", text: "Archaeology"},
	{id: "SWHS", text: "Social Work Historical and Professional"},
	{id: "ELP", text: "English Language Programs"},
	{id: "ELit", text: "English Literature"},
	{id: "LAW", text: "Law"},
	{id: "Russ St", text: "Russian Studies"},
	{id: "Ital", text: "Italian"},
	{id: "AFAS", text: "African and African-American Studies"},
	{id: "INTERD", text: "Interdisciplinary Studies"},
	{id: "PhysTher", text: "Physical Therapy"},
	{id: "Russ", text: "Russian"},
	{id: "Bio", text: "Biology"},
	{id: "SWPR", text: "Social Work Practicum"},
	{id: "MedH", text: "Medical Humanities"},
	{id: "PNP", text: "Philosophy-Neuroscience-Psychology"},
	{id: "IPH", text: "Interdisciplinary Project in the Humanities"},
	{id: "Ling", text: "Linguistics"},
	{id: "IA", text: "International & Area Studies (University College)"},
	{id: "Pol Econ", text: "Political Economy"},
	{id: "EuSt", text: "European Studies"},
	{id: "Sphr", text: "Speech and Hearing"},
	{id: "LAND", text: "Landscape Architecture"},
	{id: "E Lit", text: "English Literature"},
	{id: "Scan", text: "Scandinavian"},
	{id: "SWCR", text: "Social Work CR"},
	{id: "EECE", text: "Energy, Environmental & Chemical Engineering"},
	{id: "Praxis", text: "Praxis"},
	{id: "Comm", text: "Communications"},
	{id: "Dance", text: "Dance"},
	{id: "ESE", text: "Electrical and Systems Engineering"},
	{id: "Japan", text: "Japanese"},
	{id: "FIN", text: "Finance"},
	{id: "MEC", text: "Mechanical Engineering & Materials Science"},
	{id: "CNST", text: "Construction Management"},
	{id: "GeSt", text: "General Studies"},
	{id: "MSB", text: "Biostatistics and Genetic Epidemiology"},
	{id: "RelPol", text: "Religion and Politics"},
	{id: "MUD", text: "Master of Urban Design"},
	{id: "OMM", text: "Operations & Manufacturing Management"},
	{id: "DLA", text: "Doctor of Liberal Arts"},
	{id: "CWP", text: "College Writing Program"},
	{id: "MKT", text: "Marketing"},
	{id: "HCARE", text: "Healthcare Management"},
	{id: "Art-Arch", text: "Art-Architecture"},
	{id: "Comp Lit", text: "Comparative Literature"},
	{id: "French", text: "French"},
	{id: "SWSP", text: "Social Work SP"},
	{id: "OB", text: "Obstetrics and Gynecology"},
	{id: "HRM", text: "Human Resources Management"},
	{id: "Econ", text: "Economics"},
	{id: "IS", text: "Irish"},
	{id: "Re St", text: "Religious Studies"},
	{id: "Writing", text: "Writing"},
	{id: "IMSE", text: "Institute of Materials Science & Engineering"},
	{id: "OSCM", text: "Operations & Supply Chain Management"},
	{id: "SUST", text: "Sustainable Communities and Development"},
	{id: "CIM", text: "Computers and Information Management"},
	{id: "NPM", text: "Nonprofit Management"},
	{id: "EComp", text: "English Composition"},
	{id: "SCWK", text: "Social Work Core"},
	{id: "OSP", text: "Overseas Programs"},
	{id: "CFH", text: "Center for Honors"},
	{id: "MEMS", text: "Mechanical Engineering & Materials Science"},
	{id: "CSE", text: "Computer Science & Engineering"},
	{id: "EnSt", text: "Environmental Studies"},
	{id: "Pers", text: "Persian"},
	{id: "KOREAN", text: "Korean"},
	{id: "Hindi", text: "Hindi"},
	{id: "CRM", text: "Clinical Research Management"},
	{id: "East Asia", text: "East Asian Studies"},
	{id: "P.E.", text: "Physical Education"},
	{id: "Lw St", text: "Legal Studies"},
	{id: "Anthro", text: "Anthropology"},
	{id: "ART", text: "Art"},
	{id: "Chinese", text: "Chinese"},
	{id: "Math", text: "Math"},
	{id: "MGT", text: "Management"},
	{id: "INTL", text: "International Studies"},
	{id: "Phil", text: "Philosophy"},
	{id: "SWSA", text: "Social Work SA"},
	{id: "Pol Sci", text: "Political Science"},
	{id: "JEE", text: "Joint Electrical Engineering"},
	{id: "QBA", text: "Quantitative Business Engineering"},
	{id: "ARAB", text: "Arabic"},
	{id: "EPSc", text: "Earth & Planetary Science"},
	{id: "PolSci", text: "Political Science"},
	{id: "Latin", text: "Latin"},
	{id: "Fr", text: "French"},
	{id: "German", text: "Germanic Languages & Literatures"},
	{id: "AAS", text: "Asian American Studies"},
	{id: "BIOL", text: "Biology"},
	{id: "Drama", text: "Drama"},
	{id: "PACS", text: "Audiology and Communication Sciences"},
	{id: "IPMS", text: "Movement Science"},
	{id: "PORTUG", text: "Portuguese"},
	{id: "OT", text: "Occupational Therapy"},
	{id: "SWIP", text: "Social Work IP"},
	{id: "Phys", text: "Physical Therapy"},
	{id: "SWDT", text: "Social Work DT"},
	{id: "GS", text: "General Studies"},
	{id: "Educ", text: "Education"},
	{id: "Classics", text: "Classics"},
	{id: "SWCD", text: "Social Work CD"},
	{id: "ACCT", text: "Accounting"},
	{id: "AHBR", text: "Audiology"},
	{id: "Art", text: "Art"},
	{id: "HLTHCARE", text: "Healthcare Management"},
	{id: "Span", text: "Spanish"},
	{id: "MBB", text: "Mind-Brain-Behavior"},
	{id: "BME", text: "Biomedical Engineering"},
	{id: "JRN", text: "Journalism"},
	{id: "Path", text: "Pathfinder"},
	{id: "CLNV", text: "Clinical Investigation"}];

const majorAbbreviations = [
	{id: "CE", text: "Chemical Engineering"},
	{id: "C", text: "Chemistry"},
	{id: "CSE", text: "Computer Science"},
	{id: "GER", text: "German"},
	{id: "RUS", text: "Russian"},
	{id: "FRE", text: "French"},
	{id: "SWA", text: "Swahili"},
	{id: "POLSCI", text: "Political Science"}];

const attributeAbbreviations = [
	{id: "NSM", text: "NSM"},
	{id: "NUM", text: "NUM"},
	{id: "LCS", text: "LCS"},
	{id: "EN:H", text: "EN:H"},
	{id: "EN:S", text: "EN:S"},
];

const schoolAbbreviations = [
	{id: "A", text: "Architecture"},
	{id: "F", text: "Art"},
	{id: "L", text: "Arts & Sciences"},
	{id: "B", text: "Business"},
	{id: "X", text: "Design & Visual Arts"},
	{id: "E", text: "Engineering and Applied Science"},
	{id: "T", text: "Engineering Continuing Studies"},
	{id: "I", text: "Interdisciplinary Programs"},
	{id: "W", text: "Law"},
	{id: "M", text: "Medicine"},
	{id: "S", text: "Social Work & Public Health"},
	{id: "U", text: "University College"}
];

const abbreviations = {
	department: departmentAbbreviations,
	major: majorAbbreviations,
	attribute: attributeAbbreviations,
	school: schoolAbbreviations
};